trigger: 
  tags:
    include:
      - "*"

stages:
  - stage: Build
    jobs:
      - job: Build_Solution
        pool: Default
        timeoutInMinutes: 180
        cancelTimeoutInMinutes: 2
        steps:
          - template: .pipelines/templates/build-and-scan-solution.yml

          - template: .pipelines/templates/create-efcore-bundle.yml
            parameters:
              solutionSubfolder: AddressServiceSolution
              project: SeelansTyres.Services.AddressService
              bundleName: SeelansTyresAddressDb
              dbContext: AddressDbContext

          - template: .pipelines/templates/create-efcore-bundle.yml
            parameters:
              solutionSubfolder: OrderServiceSolution
              project: SeelansTyres.Services.OrderService
              bundleName: SeelansTyresOrderDb
              dbContext: OrderDbContext

          - template: .pipelines/templates/create-efcore-bundle.yml
            parameters:
              solutionSubfolder: TyresServiceSolution
              project: SeelansTyres.Services.TyresService
              bundleName: SeelansTyresTyresDb
              dbContext: TyresDbContext

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Frontends
              solutionSubfolder: HealthChecksUISolution
              project: SeelansTyres.Frontends.HealthChecksUI

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Frontends
              solutionSubfolder: MvcSolution
              project: SeelansTyres.Frontends.Mvc

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: FunctionApps
              solutionSubfolder: SystemDegradedTogglerSolution
              project: SeelansTyres.FunctionApps.SystemDegradedToggler
              selfContained: --self-contained

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Gateways
              solutionSubfolder: WebBffSolution
              project: SeelansTyres.Gateways.WebBff

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: AddressServiceSolution
              project: SeelansTyres.Services.AddressService

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: AddressServiceSolution
              project: SeelansTyres.Workers.AddressWorker

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: IdentityServiceSolution
              project: SeelansTyres.Services.IdentityService
              selfContained: --self-contained

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: OrderServiceSolution
              project: SeelansTyres.Services.OrderService

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: OrderServiceSolution
              project: SeelansTyres.Workers.OrderWorker

          - template: .pipelines/templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: TyresServiceSolution
              project: SeelansTyres.Services.TyresService

          - template: .pipelines/templates/final-copy-and-publish-of-artifacts.yml

          - task: GitHubRelease@1
            displayName: 'Create a New GitHub Release'
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
            inputs:
              gitHubConnection: 'ShaylenReddy42_OAuth'
              repositoryName: '$(Build.Repository.Name)'
              action: create
              tagSource: userSpecifiedTag
              tag: $(Build.SourceBranchName)
              title: 'Release v$(Build.SourceBranchName)'
              releaseNotesSource: filePath
              releaseNotesFilePath: '$(Build.SourcesDirectory)/docs/releases/v$(Build.SourceBranchName).md'
              assets: '$(Build.ArtifactStagingDirectory)/*'
              addChangeLog: false
              changeLogCompareToRelease: lastFullRelease
              changeLogType: commitBased

  - stage: Dev
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: seelanstyres-dev
    jobs:
      - job: Deploy_Infrastructure
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none
          
          - download: 'current'
            artifact: 'drop'
            patterns: '**/infrastructure/**'
            displayName: 'Download Infrastructure'
          
          - task: AzureCLI@2
            displayName: 'Deploy Infrastructure'
            inputs:
              azureSubscription: 'Azure-Manual-SP'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                $clientIP = $(Invoke-RestMethod https://ipinfo.io/json?token=$(ipInfoAccessToken)).ip
              
                az deployment sub create `
                  --template-file .\02-environment-specific\main.bicep `
                  --location southafricanorth `
                  --parameters `
                    environment=$(environment) `
                    adminCredentialsEmail=$(adminCredentialsEmail) `
                    adminCredentialsPassword=$(adminCredentialsPassword) `
                    clientIPOfAgent=$clientIP `
                    emailAddressOfResponder=$(emailAddress) `
                    emailCredentialsEmail=$(emailCredentialsEmail) `
                    emailCredentialsPassword=$(emailCredentialsPassword) `
                    healthCheckEndpoint=$(healthCheckEndpoint) `
                    mvcClientSecret=$(mvcClientSecret) `
                    webBffClientSecret=$(webBffClientSecret) `
                    sqlServerAdminLogin=$(sqlServerAdminLogin) `
                    sqlServerAdminPassword=$(sqlServerAdminPassword)
              workingDirectory: '$(Pipeline.Workspace)/drop/infrastructure/with-bicep'

      - job: Deploy_SystemDegradedTogglerSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.FunctionApps.SystemDegradedToggler.zip'
            displayName: 'Download the System-Degraded Toggler Zip'
          
          - template: .pipelines/templates/deploy-system-degraded-toggler.yml

      - job: Deploy_DatabaseSchema
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/.exe'
            displayName: 'Download EF Core Bundles'

          - template: .pipelines/templates/execute-efcore-bundle.yml
            parameters:
              bundleName: SeelansTyresAddressDb

          - template: .pipelines/templates/execute-efcore-bundle.yml
            parameters:
              bundleName: SeelansTyresOrderDb

          - template: .pipelines/templates/execute-efcore-bundle.yml
            parameters:
              bundleName: SeelansTyresTyresDb

      - job: Deploy_TyresServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Services.TyresService.zip'
            displayName: 'Download the Tyres Service Zip'

          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-tyresservice-$(environment)
              project: SeelansTyres.Services.TyresService

      - job: Deploy_OrderServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Workers.OrderWorker.zip'
            displayName: 'Download the Order Worker Zip'

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Services.OrderService.zip'
            displayName: 'Download the Order Service Zip'
          
          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-orderworker-$(environment)
              project: SeelansTyres.Workers.OrderWorker

          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-orderservice-$(environment)
              project: SeelansTyres.Services.OrderService

      - job: Deploy_IdentityServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Services.IdentityService.zip'
            displayName: 'Download the Identity Service Zip'

          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-identityservice-$(environment)
              project: SeelansTyres.Services.IdentityService

      - job: Deploy_AddressServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Workers.AddressWorker.zip'
            displayName: 'Download the Address Worker Zip'

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Services.AddressService.zip'
            displayName: 'Download the Address Service Zip'

          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-addressworker-$(environment)
              project: SeelansTyres.Workers.AddressWorker

          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-addressservice-$(environment)
              project: SeelansTyres.Services.AddressService

      - job: Deploy_WebBffSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Gateways.WebBff.zip'
            displayName: 'Download the WebBff Gateway Zip'
          
          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-webbff-$(environment)
              project: SeelansTyres.Gateways.WebBff

      - job: Deploy_MvcSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Frontends.Mvc.zip'
            displayName: 'Download the Mvc Frontend Zip'
          
          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-mvc-$(environment)
              project: SeelansTyres.Frontends.Mvc

      - job: Deploy_HealthChecksUISolution
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none

          - download: 'current'
            artifact: 'drop'
            patterns: '**/SeelansTyres.Frontends.HealthChecksUI.zip'
            displayName: 'Download the HealthChecksUI Frontend Zip'

          - template: .pipelines/templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-healthchecksui-$(environment)
              project: SeelansTyres.Frontends.HealthChecksUI
