trigger:
- '*'

pool: Default

variables:
  buildConfiguration: 'Release'
  workDir: $(Build.SourcesDirectory)

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    version: 6.0.400
    performMultiLevelLookup: true

- task: CMake@1
  displayName: 'Run CMake'
  inputs:
    workingDirectory: $(workDir)
    cmakeArgs: -S . -B "$(workDir)\build" -DCI_BUILD=ON

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: restore
    arguments: -c $(buildConfiguration)
    workingDirectory: $(workDir)

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud for Analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'shaylenreddy42'
    scannerMode: 'MSBuild'
    projectKey: 'ShaylenReddy42_Seelans-Tyres'
    projectName: 'Seelans-Tyres'
    extraProperties: |
      sonar.exclusions=**/wwwroot/lib/**,**/Migrations/**,**/Templates/**,**IdentityService/Quickstart/**,**IdentityService/Views/**
      sonar.coverage.exclusions=**/wwwroot/lib/**,**/Migrations/**,**/Templates/**,**IdentityService/Quickstart/**,**IdentityService/Views/**

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: build
    arguments: -c $(buildConfiguration)
    workingDirectory: $(workDir)

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud Quality Gate Result'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'Restore dotnet tools'
  inputs:
    command: custom
    custom: tool
    arguments: restore
    workingDirectory: '$(workDir)'

- task: DotNetCoreCLI@2
  displayName: 'Create EF Core Bundle for SeelansTyres.Services.AddressService'
  inputs:
    command: custom
    custom: tool
    arguments: run dotnet-ef migrations bundle --force --project Services/SeelansTyres.Services.AddressService/SeelansTyres.Services.AddressService.csproj --startup-project Services/SeelansTyres.Services.AddressService/SeelansTyres.Services.AddressService.csproj -o "$(Build.ArtifactStagingDirectory)\SeelansTyresAddressContext.exe"
    workingDirectory: '$(workDir)'

- task: DotNetCoreCLI@2
  displayName: 'Create EF Core Bundle for SeelansTyres.Services.OrderService'
  inputs:
    command: custom
    custom: tool
    arguments: run dotnet-ef migrations bundle --force --project Services/SeelansTyres.Services.OrderService/SeelansTyres.Services.OrderService.csproj --startup-project Services/SeelansTyres.Services.OrderService/SeelansTyres.Services.OrderService.csproj -o "$(Build.ArtifactStagingDirectory)\SeelansTyresOrderContext.exe"
    workingDirectory: '$(workDir)'

- task: DotNetCoreCLI@2
  displayName: 'Create EF Core Bundle for SeelansTyres.Services.TyresService'
  inputs:
    command: custom
    custom: tool
    arguments: run dotnet-ef migrations bundle --force --project Services/SeelansTyres.Services.TyresService/SeelansTyres.Services.TyresService.csproj --startup-project Services/SeelansTyres.Services.TyresService/SeelansTyres.Services.TyresService.csproj -o "$(Build.ArtifactStagingDirectory)\SeelansTyresTyresContext.exe"
    workingDirectory: '$(workDir)'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 --no-self-contained
  displayName: 'Publish SeelansTyres.Frontends.Mvc'
  workingDirectory: '$(workDir)\Frontends\SeelansTyres.Frontends.Mvc'

- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Frontends.Mvc'
  inputs:
    rootFolderOrFile: '$(workDir)\Frontends\SeelansTyres.Frontends.Mvc\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Frontends.Mvc.zip'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 -p:PublishSingleFile=true --no-self-contained
  displayName: 'Publish SeelansTyres.Gateways.MvcBff'
  workingDirectory: '$(workDir)\Gateways\SeelansTyres.Gateways.MvcBff'
  
- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Gateways.MvcBff'
  inputs:
    rootFolderOrFile: '$(workDir)\Gateways\SeelansTyres.Gateways.MvcBff\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Gateways.MvcBff.zip'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 -p:PublishSingleFile=true --no-self-contained
  displayName: 'Publish SeelansTyres.Services.AddressService'
  workingDirectory: '$(workDir)\Services\SeelansTyres.Services.AddressService'
  
- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Services.AddressService'
  inputs:
    rootFolderOrFile: '$(workDir)\Services\SeelansTyres.Services.AddressService\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Services.AddressService.zip'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 -p:PublishSingleFile=true --no-self-contained
  displayName: 'Publish SeelansTyres.Services.IdentityService'
  workingDirectory: '$(workDir)\Services\SeelansTyres.Services.IdentityService'
  
- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Services.IdentityService'
  inputs:
    rootFolderOrFile: '$(workDir)\Services\SeelansTyres.Services.IdentityService\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Services.IdentityService.zip'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 -p:PublishSingleFile=true --no-self-contained
  displayName: 'Publish SeelansTyres.Services.OrderService'
  workingDirectory: '$(workDir)\Services\SeelansTyres.Services.OrderService'
  
- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Services.OrderService'
  inputs:
    rootFolderOrFile: '$(workDir)\Services\SeelansTyres.Services.OrderService\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Services.OrderService.zip'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 -p:PublishSingleFile=true --no-self-contained
  displayName: 'Publish SeelansTyres.Services.TyresService'
  workingDirectory: '$(workDir)\Services\SeelansTyres.Services.TyresService'
  
- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Services.TyresService'
  inputs:
    rootFolderOrFile: '$(workDir)\Services\SeelansTyres.Services.TyresService\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Services.TyresService.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    ArtifactName: "Seelan's Tyres"