trigger:
- '*'

pool: Default

variables:
  buildConfiguration: 'Release'
  workDir: $(Build.SourcesDirectory)

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    version: 6.0.400
    performMultiLevelLookup: true

- task: CMake@1
  displayName: 'Run CMake'
  inputs:
    workingDirectory: $(workDir)
    cmakeArgs: -S . -B "$(workDir)\build" -DCI_BUILD=ON

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: restore
    arguments: -c $(buildConfiguration)
    workingDirectory: $(workDir)

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud for Analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'shaylenreddy42'
    scannerMode: 'MSBuild'
    projectKey: 'ShaylenReddy42_Seelans-Tyres'
    projectName: 'Seelans-Tyres'
    extraProperties: |
      sonar.exclusions=**/wwwroot/lib/**
      sonar.coverage.exclusions=**/wwwroot/lib/**

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: build
    arguments: -c $(buildConfiguration)
    workingDirectory: $(workDir)

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud Quality Gate Result'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'Restore dotnet tools for SeelansTyres.WebApi'
  inputs:
    command: custom
    custom: tool
    arguments: restore
    workingDirectory: '$(workDir)\SeelansTyres.WebApi'

- task: DotNetCoreCLI@2
  displayName: 'Create EF Core Bundle'
  inputs:
    command: custom
    custom: tool
    arguments: run dotnet-ef migrations bundle --force -o "$(Build.ArtifactStagingDirectory)\efbundle.exe"
    workingDirectory: '$(workDir)\SeelansTyres.WebApi'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 --no-self-contained
  displayName: 'Publish SeelansTyres.Mvc'
  workingDirectory: '$(workDir)\SeelansTyres.Mvc'

- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.Mvc'
  inputs:
    rootFolderOrFile: '$(workDir)\SeelansTyres.Mvc\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.Mvc.zip'

- script: dotnet publish -c $(buildConfiguration) -r win-x64 --no-self-contained
  displayName: 'Publish SeelansTyres.WebApi'
  workingDirectory: '$(workDir)\SeelansTyres.WebApi'

- task: ArchiveFiles@2
  displayName: 'Archive SeelansTyres.WebApi'
  inputs:
    rootFolderOrFile: '$(workDir)\SeelansTyres.WebApi\publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)\SeelansTyres.WebApi.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    ArtifactName: "Seelan's Tyres"