apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    solution: seelanstyres
  name: seelanstyres-workers-orderworker
  namespace: default
data:
  ASPNETCORE_URLS: http://*:5022

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    solution: seelanstyres
    app: seelanstyres-workers-orderworker
  name: seelanstyres-workers-orderworker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seelanstyres-workers-orderworker
  template:
    metadata:
      labels:
        app: seelanstyres-workers-orderworker
    spec:
      containers:
        - image: seelanstyres/workers/orderworker:@DOCKER_IMAGE_TAG@
          name: orderworker
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5022
          envFrom:
            - configMapRef:
                name: configmap-global
            - configMapRef:
                name: seelanstyres-workers-orderworker
            - secretRef:
                name: secrets-global
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
          startupProbe:
            tcpSocket:
              port: 5022
            initialDelaySeconds: 25
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5022
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5022
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    solution: seelanstyres
    app: seelanstyres-workers-orderworker
  name: seelanstyres-workers-orderworker
  namespace: default
spec:
  ports:
  - port: 5022
    protocol: TCP
    targetPort: 5022
  selector:
    app: seelanstyres-workers-orderworker
  type: ClusterIP
