apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    solution: seelanstyres
  name: seelanstyres-services-identityservice
data:
  ASPNETCORE_URLS: http://*:5005
  BaseUrl: https://id-local.seelanstyres.com
  envSeelansTyresMvcClientUrl: https://www-local.seelanstyres.com

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    solution: seelanstyres
    app: seelanstyres-services-identityservice
  name: seelanstyres-services-identityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seelanstyres-services-identityservice
  template:
    metadata:
      labels:
        app: seelanstyres-services-identityservice
    spec:
      containers:
        - image: seelanstyres/services/identityservice:@DOCKER_IMAGE_TAG@
          name: identityservice
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: configmap-global
            - configMapRef:
                name: seelanstyres-services-identityservice
            - secretRef:
                name: secrets-global
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          startupProbe:
            tcpSocket:
              port: 5005
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5005
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5005
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    solution: seelanstyres
    app: seelanstyres-services-identityservice
  name: seelanstyres-services-identityservice
spec:
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: seelanstyres-services-identityservice
  type: ClusterIP
