apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    solution: seelanstyres
  name: seelanstyres-services-orderservice
data:
  ASPNETCORE_URLS: http://*:5012

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    solution: seelanstyres
    app: seelanstyres-services-orderservice
  name: seelanstyres-services-orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seelanstyres-services-orderservice
  template:
    metadata:
      labels:
        app: seelanstyres-services-orderservice
    spec:
      containers:
        - image: seelanstyres/services/orderservice:@DOCKER_IMAGE_TAG@
          name: orderservice
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5012
          envFrom:
            - configMapRef:
                name: configmap-global
            - configMapRef:
                name: seelanstyres-services-orderservice
            - secretRef:
                name: secrets-global
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
          startupProbe:
            tcpSocket:
              port: 5012
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5012
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5012
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    solution: seelanstyres
    app: seelanstyres-services-orderservice
  name: seelanstyres-services-orderservice
spec:
  ports:
  - port: 5012
    protocol: TCP
    targetPort: 5012
  selector:
    app: seelanstyres-services-orderservice
  type: ClusterIP
