apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    solution: seelanstyres
  name: ingress-local-services
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - kibana-local.seelanstyres.com
      secretName: tls-for-kibana-local
    - hosts:
      - rabbitmq-local.seelanstyres.com
      secretName: tls-for-rabbitmq-local
  rules:
    - host: kibana-local.seelanstyres.com
      http:
        paths:
          - backend:
              service:
                name: kibana
                port:
                  number: 5601
            path: /
            pathType: Prefix
    - host: rabbitmq-local.seelanstyres.com
      http:
        paths:
          - backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
            path: /
            pathType: Prefix
