apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    solution: seelanstyres
  name: configmap-global
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: Development
  Database__ConnectionString: Server=sqlserver;Database=$$(Database:Name);User ID=sa;Password=P@55w0rd1234;TrustServerCertificate=true
  envUseElasticsearch: 'true'
  envElasticsearchUrl: http://elasticsearch:9200
  envRabbitMQHost: rabbitmq
  envRabbitMQPort: '5672'
  HealthCheckEndpoint: /KwjsaTB9EteliVHxBxqxogo4kMbmf2J4Fac2B3G69wTSDfczqKABwS2nnj1bT8HE4njAzE4yXHU5762w7VBlA
  IdentityServer: https://id-local.seelanstyres.com
  InContainer: 'true'
  StartupDelayInSeconds: '20'
  SystemDegraded: 'true'
