trigger:
  paths:
    include:
      - src/Services/TyresServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_TyresServiceSolution
      pool: Default
      variables:
        workDir: $(Build.SourcesDirectory)
      steps:
      - template: templates/build-and-scan-solution.yml

      - task: DotNetCoreCLI@2
        displayName: 'Restore dotnet tools'
        inputs:
          command: custom
          custom: tool
          arguments: restore
          workingDirectory: '$(workDir)'

      - task: DotNetCoreCLI@2
        displayName: 'Create EF Core Bundle for SeelansTyres.Services.TyresService'
        inputs:
          command: custom
          custom: tool
          arguments: run dotnet-ef migrations bundle --force --project src/Services/TyresServiceSolution/SeelansTyres.Services.TyresService/SeelansTyres.Services.TyresService.csproj --startup-project src/Services/TyresServiceSolution/SeelansTyres.Services.TyresService/SeelansTyres.Services.TyresService.csproj --context TyresDbContext -o "$(Build.ArtifactStagingDirectory)\SeelansTyresTyresDb.exe"
          workingDirectory: '$(workDir)'

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: TyresServiceSolution
          project: SeelansTyres.Services.TyresService
          buildImage: true
          imageName: seelanstyres/services/tyresservice

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
