trigger:
  paths:
    include:
      - src/Services/TyresServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
      - job: Build_TyresServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        steps:
          - template: templates/build-and-scan-solution.yml

          - template: templates/create-efcore-bundle.yml
            parameters:
              solutionSubfolder: TyresServiceSolution
              project: SeelansTyres.Services.TyresService
              bundleName: SeelansTyresTyresDb
              dbContext: TyresDbContext

          - template: templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: TyresServiceSolution
              project: SeelansTyres.Services.TyresService

          - template: templates/final-copy-and-publish-of-artifacts.yml

  - stage: Dev
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: seelanstyres-dev
    jobs:
      - job: Deploy_TyresServiceSolution_Dev
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - template: templates/download-artifacts-and-deploy-infrastructure.yml

          - template: templates/execute-efcore-bundle.yml
            parameters:
              bundleName: SeelansTyresTyresDb
