trigger:
  paths:
    include:
      - src/Services/OrderServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_OrderServiceSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      variables:
        workDir: $(Build.SourcesDirectory)
      steps:
      - template: templates/build-and-scan-solution.yml

      - task: DotNetCoreCLI@2
        displayName: 'Restore dotnet tools'
        inputs:
          command: custom
          custom: tool
          arguments: restore
          workingDirectory: '$(workDir)'

      - template: templates/create-efcore-bundle.yml
        parameters:
          solutionSubfolder: OrderServiceSolution
          project: SeelansTyres.Services.OrderService
          bundleName: SeelansTyresOrderDb

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: OrderServiceSolution
          project: SeelansTyres.Services.OrderService
          buildImage: true
          imageName: seelanstyres/services/orderservice

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: OrderServiceSolution
          project: SeelansTyres.Workers.OrderWorker
          buildImage: true
          imageName: seelanstyres/workers/orderworker

      - template: templates/final-copy-and-publish-of-artifacts.yml
