trigger:
  paths:
    include:
      - src/Services/IdentityServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_IdentityServiceSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      steps:
      - template: templates/build-and-scan-solution.yml

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: IdentityServiceSolution
          project: SeelansTyres.Services.IdentityService
          buildImage: true
          imageName: seelanstyres/services/identityservice

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
