trigger:
  paths:
    include:
      - src/Services/IdentityServiceSolution

stages:
  - stage: Build
    jobs:
      - job: Build_IdentityServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        steps:
          - template: templates/build-and-scan-solution.yml

          - template: templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: IdentityServiceSolution
              project: SeelansTyres.Services.IdentityService
              selfContained: --self-contained

          - template: templates/final-copy-and-publish-of-artifacts.yml

  - stage: Dev
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: seelanstyres-dev
    jobs:
      - job: Deploy_IdentityServiceSolution_Dev
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none
          
          - ${{ if eq(variables.deploySolution, 'true') }}:
            - template: templates/download-artifacts-and-deploy-infrastructure.yml

            - template: templates/deploy-webapp.yml
              parameters:
                intendedResourceName: app-seelanstyres-identityservice-$(environment)
                project: SeelansTyres.Services.IdentityService
