trigger:
  paths:
    include:
      - src/Services/OrderServiceSolution

stages:
  - stage: Build
    jobs:
      - job: Build_OrderServiceSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        steps:
          - template: templates/build-and-scan-solution.yml

          - template: templates/create-efcore-bundle.yml
            parameters:
              solutionSubfolder: OrderServiceSolution
              project: SeelansTyres.Services.OrderService
              bundleName: SeelansTyresOrderDb
              dbContext: OrderDbContext

          - template: templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: OrderServiceSolution
              project: SeelansTyres.Services.OrderService

          - template: templates/publish-project.yml
            parameters:
              solutionFolder: Services
              solutionSubfolder: OrderServiceSolution
              project: SeelansTyres.Workers.OrderWorker

          - template: templates/final-copy-and-publish-of-artifacts.yml

  - stage: Dev
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: seelanstyres-dev
    jobs:
      - job: Deploy_OrderServiceSolution_Dev
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - checkout: none
          
          - ${{ if eq(variables.deploySolution, 'true') }}:
            - template: templates/download-artifacts-and-deploy-infrastructure.yml

            - template: templates/execute-efcore-bundle.yml
              parameters:
                bundleName: SeelansTyresOrderDb

            - template: templates/deploy-webapp.yml
              parameters:
                intendedResourceName: app-seelanstyres-orderservice-$(environment)
                project: SeelansTyres.Services.OrderService

            - template: templates/deploy-webapp.yml
              parameters:
                intendedResourceName: app-seelanstyres-orderworker-$(environment)
                project: SeelansTyres.Workers.OrderWorker
