trigger:
  paths:
    include:
      - src/Services/AddressServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_AddressServiceSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      steps:
      - template: templates/build-and-scan-solution.yml

      - template: templates/create-efcore-bundle.yml
        parameters:
          solutionSubfolder: AddressServiceSolution
          project: SeelansTyres.Services.AddressService
          bundleName: SeelansTyresAddressDb

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: AddressServiceSolution
          project: SeelansTyres.Services.AddressService
          buildImage: true
          imageName: seelanstyres/services/addressservice

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: AddressServiceSolution
          project: SeelansTyres.Workers.AddressWorker
          buildImage: true
          imageName: seelanstyres/workers/addressworker

      - template: templates/final-copy-and-publish-of-artifacts.yml
