trigger:
  paths:
    include:
      - src/Services/AddressServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_AddressServiceSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      variables:
        workDir: $(Build.SourcesDirectory)
      steps:
      - template: templates/build-and-scan-solution.yml

      - task: DotNetCoreCLI@2
        displayName: 'Restore dotnet tools'
        inputs:
          command: custom
          custom: tool
          arguments: restore
          workingDirectory: '$(workDir)'

      - task: DotNetCoreCLI@2
        displayName: 'Create EF Core Bundle for SeelansTyres.Services.AddressService'
        inputs:
          command: custom
          custom: tool
          arguments: run dotnet-ef migrations bundle --force --project src/Services/AddressServiceSolution/SeelansTyres.Services.AddressService/SeelansTyres.Services.AddressService.csproj --startup-project src/Services/AddressServiceSolution/SeelansTyres.Services.AddressService/SeelansTyres.Services.AddressService.csproj -o "$(Build.ArtifactStagingDirectory)\SeelansTyresAddressDb.exe"
          workingDirectory: '$(workDir)'

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: AddressServiceSolution
          project: SeelansTyres.Services.AddressService
          buildImage: true
          imageName: seelanstyres/services/addressservice

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: AddressServiceSolution
          project: SeelansTyres.Workers.AddressWorker
          buildImage: true
          imageName: seelanstyres/workers/addressworker

      - template: templates/final-copy-and-publish-of-artifacts.yml
