trigger:
  paths:
    include:
      - src/Frontends/MvcSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_MvcSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      steps:
      - template: templates/build-and-scan-solution.yml

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Frontends
          solutionSubfolder: MvcSolution
          project: SeelansTyres.Frontends.Mvc
          buildImage: true
          imageName: seelanstyres/frontends/mvc

      - template: templates/final-copy-and-publish-of-artifacts.yml
