trigger:
  paths:
    include:
      - src/Services/TyresServiceSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_TyresServiceSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      steps:
      - template: templates/build-and-scan-solution.yml

      - template: templates/create-efcore-bundle.yml
        parameters:
          solutionSubfolder: TyresServiceSolution
          project: SeelansTyres.Services.TyresService
          bundleName: SeelansTyresTyresDb

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Services
          solutionSubfolder: TyresServiceSolution
          project: SeelansTyres.Services.TyresService
          buildImage: true
          imageName: seelanstyres/services/tyresservice

      - template: templates/final-copy-and-publish-of-artifacts.yml
