trigger:
  paths:
    include:
      - src/Frontends/MvcSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
      - job: Build_MvcSolution
        pool: Default
        cancelTimeoutInMinutes: 2
        steps:
          - template: templates/build-and-scan-solution.yml

          - template: templates/publish-project.yml
            parameters:
              solutionFolder: Frontends
              solutionSubfolder: MvcSolution
              project: SeelansTyres.Frontends.Mvc

          - template: templates/final-copy-and-publish-of-artifacts.yml

  - stage: Dev
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: seelanstyres-dev
    jobs:
      - job: Deploy_MvcSolution_Dev
        pool: Default
        cancelTimeoutInMinutes: 2
        timeoutInMinutes: 120
        steps:
          - template: templates/download-artifacts-and-deploy-infrastructure.yml

          - template: templates/deploy-webapp.yml
            parameters:
              intendedResourceName: app-seelanstyres-mvc-$(environment)
              project: SeelansTyres.Frontends.Mvc
