trigger:
  paths:
    include:
      - src/Gateways/MvcBffSolution
      - src/Libraries/SharedLibrarySolution

stages:
  - stage: Build
    jobs:
    - job: Build_MvcBffSolution
      pool: Default
      cancelTimeoutInMinutes: 2
      steps:
      - template: templates/build-and-scan-solution.yml

      - template: templates/publish-project.yml
        parameters:
          solutionFolder: Gateways
          solutionSubfolder: MvcBffSolution
          project: SeelansTyres.Gateways.MvcBff
          buildImage: true
          imageName: seelanstyres/gateways/mvcbff

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
