version: '3.8'

services:
  
  # Frontends ###########################################################################################
  
  seelanstyres-frontends-healthchecksui:
    build:
      context: ../../src/
      dockerfile: 'Frontends/HealthChecksUISolution/SeelansTyres.Frontends.HealthChecksUI/Dockerfile'
    container_name: 'seelanstyres_frontends_healthchecksui'
    image: 'seelanstyres/frontends/healthchecksui:${TAG}'
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - Host=${HOST}
      - InContainer=true
    restart: always
    networks:
      - seelanstyres-network
  
  seelanstyres-frontends-mvc:
    build:
      context: ../../src/
      dockerfile: 'Frontends/MvcSolution/SeelansTyres.Frontends.Mvc/Dockerfile'
    container_name: 'seelanstyres_frontends_mvc'
    image: 'seelanstyres/frontends/mvc:${TAG}'
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - EmailCredentials__Email=${EmailCredentials__Email}
      - EmailCredentials__Password=${EmailCredentials__Password}
      - IdentityServer=${IDENTITYSERVER}
      - envMvcBffUrl=http://${HOST}:5050
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - InContainer=true
    volumes:
      - ../volumes/images:/app/wwwroot/images/uploaded
    restart: always
    networks:
      - seelanstyres-network

  # Gateways ############################################################################################

  seelanstyres-gateways-mvcbff:
    build:
      context: ../../src/
      dockerfile: 'Gateways/MvcBffSolution/SeelansTyres.Gateways.MvcBff/Dockerfile'
    container_name: 'seelanstyres_gateways_mvcbff'
    image: 'seelanstyres/gateways/mvcbff:${TAG}'
    ports:
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5050
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - envAddressServiceHost=${HOST}
      - envCustomerServiceHost=id-local.seelanstyres.com
      - envOrderServiceHost=${HOST}
      - envTyresServiceHost=${HOST}
      - envBaseUrl=http://${HOST}:5050
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
      - Services__CustomerService__Scheme=https
      - Services__CustomerService__Port=4000
    restart: always
    networks:
      - seelanstyres-network

  # Services ############################################################################################

  seelanstyres-services-addressservice:
    build:
      context: ../../src/
      dockerfile: 'Services/AddressServiceSolution/SeelansTyres.Services.AddressService/Dockerfile'
    container_name: 'seelanstyres_services_addressservice'
    image: 'seelanstyres/services/addressservice:${TAG}'
    ports:
      - 5011:5011
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5011
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
    depends_on:
      - sqlserver
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-identityservice:
    build:
      context: ../../src/
      dockerfile: 'Services/IdentityServiceSolution/SeelansTyres.Services.IdentityService/Dockerfile'
    container_name: 'seelanstyres_services_identityservice'
    image: 'seelanstyres/services/identityservice:${TAG}'
    ports:
      - 5005:5005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5005
      - AdminCredentials__Email=${AdminCredentials__Email}
      - AdminCredentials__Password=${AdminCredentials__Password}
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - BaseUrl=${IDENTITYSERVER}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envSeelansTyresMvcClientUrl=https://www-local.seelanstyres.com:4000
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
    depends_on:
      - sqlserver
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-orderservice:
    build:
      context: ../../src/
      dockerfile: 'Services/OrderServiceSolution/SeelansTyres.Services.OrderService/Dockerfile'
    container_name: 'seelanstyres_services_orderservice'
    image: 'seelanstyres/services/orderservice:${TAG}'
    ports:
      - 5012:5012
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5012
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
    depends_on:
      - sqlserver
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-tyresservice:
    build:
      context: ../../src/
      dockerfile: 'Services/TyresServiceSolution/SeelansTyres.Services.TyresService/Dockerfile'
    container_name: 'seelanstyres_services_tyresservice'
    image: 'seelanstyres/services/tyresservice:${TAG}'
    ports:
      - 5013:5013
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5013
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
    depends_on:
      - sqlserver
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  # Workers #############################################################################################

  seelanstyres-workers-addressworker:
    build:
      context: ../../src/
      dockerfile: 'Services/AddressServiceSolution/SeelansTyres.Workers.AddressWorker/Dockerfile'
    container_name: 'seelanstyres_workers_addressworker'
    image: 'seelanstyres/workers/addressworker:${TAG}'
    ports:
      - 5021:5021
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5021
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-workers-orderworker:
    build:
      context: ../../src/
      dockerfile: 'Services/OrderServiceSolution/SeelansTyres.Workers.OrderWorker/Dockerfile'
    container_name: 'seelanstyres_workers_orderworker'
    image: 'seelanstyres/workers/orderworker:${TAG}'
    ports:
      - 5022:5022
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5022
      - AppInsights__Enabled=${AppInsights__Enabled}
      - AppInsights__ConnectionString=${AppInsights__ConnectionString}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - IdentityServer=${IDENTITYSERVER}
      - InContainer=true
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  # Important Services ##################################################################################

  nginx:
    build:
      context: ../custom-images/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    image: customnginx
    ports:
      - 4000:4000
    depends_on:
      - seelanstyres-services-identityservice
      - seelanstyres-frontends-mvc
    restart: always
    networks:
      seelanstyres-network:
        aliases:
          - id-local.seelanstyres.com
          - www-local.seelanstyres.com

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@55w0rd1234
    volumes:
      - ../volumes/mssql/data:/var/opt/mssql/data
    restart: always
    networks:
      - seelanstyres-network

  # Other Services ######################################################################################

  elasticsearch:
    image: elasticsearch:7.17.8
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elasticsearch
      - cluster.name=seelanstyres-cluster
      - discovery.type=single-node
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ../volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - seelanstyres-network

  kibana:
    image: kibana:7.17.8
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    networks:
      - seelanstyres-network

  rabbitmq:
    build:
      context: ../custom-images/rabbitmq/
      dockerfile: Dockerfile
    container_name: rabbitmq
    image: customrabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - seelanstyres-network

networks:
  seelanstyres-network:
    driver: bridge
    name: seelanstyres-network
