version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: elasticsearch
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      - node.name=elasticsearch
      - cluster.name=seelanstyres-cluster
      - discovery.type=single-node
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ../volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - services-network

  kibana:
    image: kibana:7.17.12
    container_name: kibana
    ports:
      - 5602:5601
    restart: always
    networks:
      - services-network
  
  rabbitmq:
    build:
      context: ../custom-images/rabbitmq/
      dockerfile: Dockerfile
    container_name: rabbitmq
    image: customrabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - services-network

networks:
  services-network:
    driver: bridge
    name: services-network