version: '3.8'

services:
  seelanstyres-frontends-healthchecksui:
    build:
      context: ../../src/
      dockerfile: 'Frontends/HealthChecksUISolution/SeelansTyres.Frontends.HealthChecksUI/Dockerfile'
    container_name: 'seelanstyres_frontends_healthchecksui'
    image: 'seelanstyres/frontends/healthchecksui:${TAG}'
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - GlobalHealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envHost=${HOST}
      - UseDocker=true
    restart: always
    networks:
      - seelanstyres-network
  
  seelanstyres-frontends-mvc:
    build:
      context: ../../src/
      dockerfile: 'Frontends/MvcSolution/SeelansTyres.Frontends.Mvc/Dockerfile'
    container_name: 'seelanstyres_frontends_mvc'
    image: 'seelanstyres/frontends/mvc:${TAG}'
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EmailCredentials__Email=${EmailCredentials__Email}
      - EmailCredentials__Password=${EmailCredentials__Password}
      - envIdentityServerUrl=http://${HOST}:5005
      - envMvcBffUrl=http://${HOST}:5050
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - SystemDegraded=true
      - UseDocker=true
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-gateways-mvcbff:
    build:
      context: ../../src/
      dockerfile: 'Gateways/MvcBffSolution/SeelansTyres.Gateways.MvcBff/Dockerfile'
    container_name: 'seelanstyres_gateways_mvcbff'
    image: 'seelanstyres/gateways/mvcbff:${TAG}'
    ports:
      - 5050:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - envAddressServiceHost=${HOST}
      - envCustomerServiceHost=${HOST}
      - envOrderServiceHost=${HOST}
      - envTyresServiceHost=${HOST}
      - envBaseUrl=http://${HOST}:5050
      - envIdentityServerUrl=http://${HOST}:5005
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - UseDocker=true
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-addressservice:
    build:
      context: ../../src/
      dockerfile: 'Services/AddressServiceSolution/SeelansTyres.Services.AddressService/Dockerfile'
    container_name: 'seelanstyres_services_addressservice'
    image: 'seelanstyres/services/addressservice:${TAG}'
    ports:
      - 5011:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envTokenIssuer=http://${HOST}:5005
      - UseDocker=true
    depends_on:
      - sqlserver
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-addressworker:
    build:
      context: ../../src/
      dockerfile: 'Services/AddressServiceSolution/SeelansTyres.Workers.AddressWorker/Dockerfile'
    container_name: 'seelanstyres_workers_addressworker'
    image: 'seelanstyres/workers/addressworker:${TAG}'
    ports:
      - 5021:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - envTokenIssuer=http://${HOST}:5005
      - UseDocker=true
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-identityservice:
    build:
      context: ../../src/
      dockerfile: 'Services/IdentityServiceSolution/SeelansTyres.Services.IdentityService/Dockerfile'
    container_name: 'seelanstyres_services_identityservice'
    image: 'seelanstyres/services/identityservice:${TAG}'
    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AdminCredentials__Email=${AdminCredentials__Email}
      - AdminCredentials__Password=${AdminCredentials__Password}
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envBaseUrl=http://${HOST}:5005
      - envSeelansTyresMvcClientUrl=http://${HOST}:5001
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - UseDocker=true
    depends_on:
      - sqlserver
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-orderservice:
    build:
      context: ../../src/
      dockerfile: 'Services/OrderServiceSolution/SeelansTyres.Services.OrderService/Dockerfile'
    container_name: 'seelanstyres_services_orderservice'
    image: 'seelanstyres/services/orderservice:${TAG}'
    ports:
      - 5012:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envTokenIssuer=http://${HOST}:5005
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - UseDocker=true
    depends_on:
      - sqlserver
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-orderworker:
    build:
      context: ../../src/
      dockerfile: 'Services/OrderServiceSolution/SeelansTyres.Workers.OrderWorker/Dockerfile'
    container_name: 'seelanstyres_workers_orderworker'
    image: 'seelanstyres/workers/orderworker:${TAG}'
    ports:
      - 5022:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - envTokenIssuer=http://${HOST}:5005
      - UseDocker=true
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  seelanstyres-services-tyresservice:
    build:
      context: ../../src/
      dockerfile: 'Services/TyresServiceSolution/SeelansTyres.Services.TyresService/Dockerfile'
    container_name: 'seelanstyres_services_tyresservice'
    image: 'seelanstyres/services/tyresservice:${TAG}'
    ports:
      - 5013:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=${DBCONNECTIONSTRING}
      - envTokenIssuer=http://${HOST}:5005
      - envUseElasticsearch=true
      - envElasticsearchUrl=${ELASTICSEARCH}
      - HealthCheckEndpoint=${DOCKERHEALTHCHECKENDPOINT}
      - envRabbitMQHost=${HOST}
      - envRabbitMQPort=5672
      - UseDocker=true
    depends_on:
      - sqlserver
      - rabbitmq
    restart: always
    networks:
      - seelanstyres-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@55w0rd1234
    volumes:
      - ../../docker/mssql/data:/var/opt/mssql/data
      - ../../docker/mssql/log:/var/opt/mssql/log
      - ../../docker/mssql/secrets:/var/opt/mssql/secrets
    restart: always
    networks:
      - seelanstyres-network

  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elasticsearch
      - cluster.name=seelanstyres-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ../../docker/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - seelanstyres-network

  kibana:
    image: kibana:7.17.7
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    networks:
      - seelanstyres-network
  
  rabbitmq:
    build:
      context: ../custom-images/rabbitmq/
      dockerfile: Dockerfile
    container_name: rabbitmq
    image: customrabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - seelanstyres-network

networks:
  seelanstyres-network:
    driver: bridge
    name: seelanstyres-network