version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      - node.name=elasticsearch
      - cluster.name=seelanstyres-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ../../docker/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - loggingsinks-network

  kibana:
    image: kibana:7.17.6
    container_name: kibana
    ports:
      - 5602:5601
    restart: always
    networks:
      - loggingsinks-network

networks:
  loggingsinks-network:
    driver: bridge
    name: loggingsinks-network